9
0D:\gitproject\CrudRepNUnit\CF.Data\BaseEntity.csutf-8<
3D:\gitproject\CrudRepNUnit\CF.Data\CurdDbContext.csutf-8:
1D:\gitproject\CrudRepNUnit\CF.Data\Departement.csutf-8`
WD:\gitproject\CrudRepNUnit\CF.Data\Migrations\201711201013569_CurdDbContext.Designer.csutf-8W
ND:\gitproject\CrudRepNUnit\CF.Data\Migrations\201711201013569_CurdDbContext.csutf-8G
>D:\gitproject\CrudRepNUnit\CF.Data\Migrations\Configuration.csutf-8F
=D:\gitproject\CrudRepNUnit\CF.Data\Properties\AssemblyInfo.csutf-86
-D:\gitproject\CrudRepNUnit\CF.Data\Student.csutf-89
0D:\gitproject\CrudRepNUnit\CF.Data\StudentMap.csutf-8H
?D:\gitproject\CrudRepNUnit\CF.Data\dbToModelEntities.Context.csutf-8I
@D:\gitproject\CrudRepNUnit\CF.Data\dbToModelEntities.Designer.csutf-8@
7D:\gitproject\CrudRepNUnit\CF.Data\dbToModelEntities.csutf-8t
kD:\gitproject\CrudRepNUnit\CF.Data\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8t
kD:\gitproject\CrudRepNUnit\CF.Data\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8t
kD:\gitproject\CrudRepNUnit\CF.Data\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8A
8D:\gitproject\CrudRepNUnit\CF.Repo\Common\IRepository.csutf-8A
8D:\gitproject\CrudRepNUnit\CF.Repo\Common\IUnitOfWork.csutf-8@
7D:\gitproject\CrudRepNUnit\CF.Repo\Common\Repository.csutf-8@
7D:\gitproject\CrudRepNUnit\CF.Repo\Common\UnitOfWork.csutf-8D
;D:\gitproject\CrudRepNUnit\CF.Repo\DepartementRepository.csutf-8E
<D:\gitproject\CrudRepNUnit\CF.Repo\IDepartementRepository.csutf-8A
8D:\gitproject\CrudRepNUnit\CF.Repo\IStudentRepository.csutf-8F
=D:\gitproject\CrudRepNUnit\CF.Repo\Properties\AssemblyInfo.csutf-8@
7D:\gitproject\CrudRepNUnit\CF.Repo\StudentRepository.csutf-8t
kD:\gitproject\CrudRepNUnit\CF.Repo\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8t
kD:\gitproject\CrudRepNUnit\CF.Repo\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8t
kD:\gitproject\CrudRepNUnit\CF.Repo\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8F
=D:\gitproject\CrudRepNUnit\CF.Service\Common\EntityService.csutf-8G
>D:\gitproject\CrudRepNUnit\CF.Service\Common\IEntityService.csutf-8A
8D:\gitproject\CrudRepNUnit\CF.Service\Common\IService.csutf-8D
;D:\gitproject\CrudRepNUnit\CF.Service\DepartementService.csutf-8E
<D:\gitproject\CrudRepNUnit\CF.Service\IDepartementService.csutf-8A
8D:\gitproject\CrudRepNUnit\CF.Service\IStudentService.csutf-8I
@D:\gitproject\CrudRepNUnit\CF.Service\Properties\AssemblyInfo.csutf-8@
7D:\gitproject\CrudRepNUnit\CF.Service\StudentService.csutf-8w
nD:\gitproject\CrudRepNUnit\CF.Service\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8w
nD:\gitproject\CrudRepNUnit\CF.Service\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8w
nD:\gitproject\CrudRepNUnit\CF.Service\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8K
BD:\gitproject\CrudRepNUnit\CURDCodeFirst\App_Start\BundleConfig.csutf-8J
AD:\gitproject\CrudRepNUnit\CURDCodeFirst\App_Start\RouteConfig.csutf-8C
:D:\gitproject\CrudRepNUnit\CURDCodeFirst\Code\ModelSize.csutf-8R
ID:\gitproject\CrudRepNUnit\CURDCodeFirst\Controllers\StudentController.csutf-8@
7D:\gitproject\CrudRepNUnit\CURDCodeFirst\Global.asax.csutf-8J
AD:\gitproject\CrudRepNUnit\CURDCodeFirst\Models\BootstrapModel.csutf-8G
>D:\gitproject\CrudRepNUnit\CURDCodeFirst\Models\ModalFooter.csutf-8G
>D:\gitproject\CrudRepNUnit\CURDCodeFirst\Models\ModalHeader.csutf-8L
CD:\gitproject\CrudRepNUnit\CURDCodeFirst\Models\StudentViewModel.csutf-8L
CD:\gitproject\CrudRepNUnit\CURDCodeFirst\Properties\AssemblyInfo.csutf-8z
qD:\gitproject\CrudRepNUnit\CURDCodeFirst\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8z
qD:\gitproject\CrudRepNUnit\CURDCodeFirst\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8z
qD:\gitproject\CrudRepNUnit\CURDCodeFirst\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8H
?D:\gitproject\CrudRepNUnit\CrudRepository\ContainerExtension.csutf-8V
MD:\gitproject\CrudRepNUnit\CrudRepository\Controller\DepartementController.csutf-8R
ID:\gitproject\CrudRepNUnit\CrudRepository\Controller\StudentController.csutf-8P
GD:\gitproject\CrudRepNUnit\CrudRepository\DialogLibrary\KarenDialogs.csutf-8I
@D:\gitproject\CrudRepNUnit\CrudRepository\EditorForm.Designer.csutf-8@
7D:\gitproject\CrudRepNUnit\CrudRepository\EditorForm.csutf-8D
;D:\gitproject\CrudRepNUnit\CrudRepository\Form1.Designer.csutf-8;
2D:\gitproject\CrudRepNUnit\CrudRepository\Form1.csutf-8F
=D:\gitproject\CrudRepNUnit\CrudRepository\FrmMain.Designer.csutf-8=
4D:\gitproject\CrudRepNUnit\CrudRepository\FrmMain.csutf-8`
WD:\gitproject\CrudRepNUnit\CrudRepository\LanguageExtensions\BindingSourceExtensions.csutf-8S
JD:\gitproject\CrudRepNUnit\CrudRepository\LanguageExtensions\Extensions.csutf-8P
GD:\gitproject\CrudRepNUnit\CrudRepository\Ninject\ApplicationModule .csutf-8M
DD:\gitproject\CrudRepNUnit\CrudRepository\Ninject\CompositionRoot.csutf-8=
4D:\gitproject\CrudRepNUnit\CrudRepository\Program.csutf-8M
DD:\gitproject\CrudRepNUnit\CrudRepository\Properties\AssemblyInfo.csutf-8S
JD:\gitproject\CrudRepNUnit\CrudRepository\Properties\Resources.Designer.csutf-8R
ID:\gitproject\CrudRepNUnit\CrudRepository\Properties\Settings.Designer.csutf-8I
@D:\gitproject\CrudRepNUnit\CrudRepository\SortableBindingList.csutf-8M
DD:\gitproject\CrudRepNUnit\CrudRepository\Utils\Nlog\MyLogManager.csutf-8R
ID:\gitproject\CrudRepNUnit\CrudRepository\frmManageDepartment.Designer.csutf-8I
@D:\gitproject\CrudRepNUnit\CrudRepository\frmManageDepartment.csutf-8{
rD:\gitproject\CrudRepNUnit\CrudRepository\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8{
rD:\gitproject\CrudRepNUnit\CrudRepository\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8{
rD:\gitproject\CrudRepNUnit\CrudRepository\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8K
BD:\gitproject\CrudRepNUnit\SampleRepository\EditorForm.Designer.csutf-8B
9D:\gitproject\CrudRepNUnit\SampleRepository\EditorForm.csutf-8F
=D:\gitproject\CrudRepNUnit\SampleRepository\Form1.Designer.csutf-8=
4D:\gitproject\CrudRepNUnit\SampleRepository\Form1.csutf-8?
6D:\gitproject\CrudRepNUnit\SampleRepository\Program.csutf-8O
FD:\gitproject\CrudRepNUnit\SampleRepository\Properties\AssemblyInfo.csutf-8U
LD:\gitproject\CrudRepNUnit\SampleRepository\Properties\Resources.Designer.csutf-8T
KD:\gitproject\CrudRepNUnit\SampleRepository\Properties\Settings.Designer.csutf-8}
tD:\gitproject\CrudRepNUnit\SampleRepository\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8}
tD:\gitproject\CrudRepNUnit\SampleRepository\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8}
tD:\gitproject\CrudRepNUnit\SampleRepository\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8G
>D:\gitproject\CrudRepNUnit\UnitTest\Properties\AssemblyInfo.csutf-8B
9D:\gitproject\CrudRepNUnit\UnitTest\ServiceStudentTest.csutf-8u
lD:\gitproject\CrudRepNUnit\UnitTest\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8u
lD:\gitproject\CrudRepNUnit\UnitTest\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8u
lD:\gitproject\CrudRepNUnit\UnitTest\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8